---
title: "Tutorials"
output: github_document
---


Tutoriais, maioria em R, alguns Python. Por enquanto, maioria deles dizem respeito à geração de mapas de distribuição de algumas poucas espécies de plantas, oriundas de minha [carreira profissional em Botânica](https://github.com/ricoperdiz/CV).

Tutoriais disponíveis:

* Plotar mapa de [**A new species of _Macrolobium_ (Fabaceae, Detarioideae) endemic on a Tepui of the Guyana Shield in Brazil** (Farronay et al. 2018)](https://www.researchgate.net/publication/326475093_A_new_species_of_Macrolobium_Fabaceae_Detarioideae_endemic_on_a_Tepui_of_the_Guyana_Shield_in_Brazil)

* Plotar mapa de [**Novas ocorrências de angiospermas para o estado de Roraima, Brasil** (Rodrigues et al. 2017](https://www.researchgate.net/publication/317671892_Novas_ocorrencias_de_angiospermas_para_o_estado_de_Roraima_Brasil).

* Plotar mapa de [**Rediscovery of _Pilosocereus oligolepsis_ (Cactaceae) in the State of Roraima, Brazil** (Lavor et al. 2016)](https://www.researchgate.net/publication/304000968_Rediscovery_of_Pilosocereus_oligolepsis_Cactaceae_in_the_State_of_Roraima_Brazil)

***

Tutorials mostly in R and a few of Python. By this time, most of them are about plotting published distribution maps of few plant species of my [own research as a botanist](https://github.com/ricoperdiz/CV).

